version: '3'

services:
  traefik:
    image: traefik:1.7
    container_name: traefik
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - /srv/traefik/acme.json:/acme.json

networks:
  web:
    external: true
